version: "3"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=wortex
      - POSTGRES_PASSWORD=1234
    container_name: "wortexPostgres"
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: